##
## Makefile for arduino-mk in /home/korrigan/dev/arduino-mk/lib/Ethernet
## 
## Made by Matthieu Rosinski
## Login   <korrigan@epitech.net>
## 
## Started on  Sun Jul 17 16:48:41 2011 Matthieu Rosinski
## Last update Sun Jul 17 16:48:41 2011 Matthieu Rosinski
##

NAME		=	libethernet.a

SRC		=	utility/socket.c \
			utility/w5100.c

CXXSRC		=	Client.cpp \
			Server.cpp \
			Ethernet.cpp

CFLAGS		+=	-Iutility
CXXFLAGS	+=	-Iutility

include	../Makefile
